/**
 * Localization System for EduAI Landing Page
 * Multi-language support with Turkish as primary language
 */

import type { 
  HeroContent, 
  FeatureItem, 
  WorkflowStep, 
  StatisticItem, 
  TestimonialItem, 
  CTAContent, 
  FooterContent 
} from '../data/content';

// Localized content interface
export interface LocalizedContent {
  hero: HeroContent;
  features: FeatureItem[];
  workflow: WorkflowStep[];
  statistics: StatisticItem[];
  testimonials: TestimonialItem[];
  cta: CTAContent;
  footer: FooterContent;
}

// English translations
export const englishContent: LocalizedContent = {
  hero: {
    title: "AI-Powered Personalized Learning Experience",
    subtitle: "The Future of Education Technology",
    description: "Reach your learning goals faster with EduAI's AI-powered question generation, detailed performance analysis, and personalized book recommendations. Thousands of students have improved their academic success.",
    primaryCTA: {
      text: "Start Free",
      href: "/register",
      ariaLabel: "Sign up for EduAI free trial"
    },
    secondaryCTA: {
      text: "Watch Demo",
      href: "/demo",
      ariaLabel: "Watch EduAI platform demo video"
    },
    features: [
      "AI-powered question generation",
      "Detailed performance analysis",
      "Personalized learning",
      "24/7 support"
    ],
    trustIndicators: {
      userCount: "50,000+",
      rating: 4.8,
      testimonialPreview: "My math grades improved by 40% thanks to EduAI!"
    }
  },
  
  features: [
    {
      id: "ai-questions",
      title: "AI-Powered Question Generation",
      description: "Personalized questions automatically generated by AI algorithms tailored to your level.",
      icon: "brain",
      benefits: [
        "Level-appropriate question difficulty",
        "Focus on weak topics",
        "Unlimited question pool",
        "Updated curriculum compliance"
      ],
      stats: {
        value: "1M+",
        label: "Generated Questions"
      }
    },
    {
      id: "performance-analysis",
      title: "Detailed Performance Analysis",
      description: "Track your progress, discover your strengths and weaknesses, focus on your goals.",
      icon: "analytics",
      benefits: [
        "Real-time analysis",
        "Topic-based success rates",
        "Learning speed tracking",
        "Comparative reports"
      ],
      stats: {
        value: "95%",
        label: "Success Improvement"
      }
    },
    {
      id: "book-recommendations",
      title: "Personalized Book Recommendations",
      description: "Get the best book and resource recommendations tailored to your needs with AI algorithms.",
      icon: "book",
      benefits: [
        "Level-based recommendations",
        "Focus on topic deficiencies",
        "Updated resource database",
        "User reviews"
      ],
      stats: {
        value: "10K+",
        label: "Book Database"
      }
    },
    {
      id: "personalized-learning",
      title: "Adaptive Learning System",
      description: "Provides personalized educational experience tailored to each student's learning style.",
      icon: "user",
      benefits: [
        "Individual learning pace",
        "Preferred learning style",
        "Flexible study schedule",
        "Motivation tracking system"
      ],
      stats: {
        value: "85%",
        label: "Motivation Increase"
      }
    }
  ],

  workflow: [
    {
      id: "register",
      step: 1,
      title: "Sign Up",
      description: "Join the EduAI family with quick and easy registration.",
      icon: "user-plus",
      details: [
        "30-second email registration",
        "Enter your basic information",
        "Complete email verification",
        "Complete your profile"
      ],
      duration: "2 minutes"
    },
    {
      id: "select-subjects",
      step: 2,
      title: "Subject Selection",
      description: "Choose the subjects you want to study and set your goals.",
      icon: "book-open",
      details: [
        "Select your interests",
        "Determine your current level",
        "Set your target level",
        "Create your study plan"
      ],
      duration: "3 minutes"
    },
    {
      id: "ai-practice",
      step: 3,
      title: "AI-Assisted Study",
      description: "Practice with personalized questions and track your progress.",
      icon: "brain",
      details: [
        "Level-appropriate questions",
        "Instant feedback",
        "Error analysis and suggestions",
        "Adaptive difficulty adjustment"
      ],
      duration: "Continuous"
    },
    {
      id: "track-progress",
      step: 4,
      title: "Progress Tracking",
      description: "Monitor your development with detailed reports and reach your goals.",
      icon: "chart",
      details: [
        "Daily progress reports",
        "Weekly success analysis",
        "Topic-based performance",
        "Goal tracking system"
      ],
      duration: "Daily"
    }
  ],

  statistics: [
    {
      id: "users",
      value: 50000,
      label: "Active Users",
      description: "Number of students continuing their learning journey with EduAI",
      icon: "users",
      suffix: "+"
    },
    {
      id: "questions",
      value: 2500000,
      label: "Questions Solved",
      description: "Total number of questions successfully solved on the platform",
      icon: "question",
      format: "number",
      suffix: "+"
    },
    {
      id: "success-rate",
      value: 87.5,
      label: "Success Rate",
      description: "Average increase in users' academic success",
      icon: "trophy",
      format: "percentage",
      suffix: "%"
    },
    {
      id: "satisfaction",
      value: 4.8,
      label: "User Satisfaction",
      description: "Average user satisfaction score out of 5",
      icon: "star",
      format: "decimal",
      suffix: "/5"
    }
  ],

  testimonials: [
    {
      id: "testimonial-1",
      name: "Ahmed Wilson",
      role: "11th Grade Student",
      company: "Science High School",
      avatar: "/images/testimonials/ahmed-w.jpg",
      rating: 5,
      content: "Thanks to EduAI, I discovered my gaps in math topics and increased my grades by 40% through targeted studying. The AI-powered questions were really suitable for my level.",
      date: "2024-12-15",
      featured: true,
      tags: ["mathematics", "highschool", "success"]
    },
    {
      id: "testimonial-2",
      name: "Sarah Johnson",
      role: "University Student",
      company: "MIT Computer Engineering",
      avatar: "/images/testimonials/sarah-j.jpg",
      rating: 5,
      content: "While preparing for university exams, I got into my target department thanks to EduAI's personalized study plan and detailed analyses.",
      date: "2024-11-28",
      featured: true,
      tags: ["university", "exam", "success"]
    },
    {
      id: "testimonial-3",
      name: "Michael Brown",
      role: "8th Grade Student",
      avatar: "/images/testimonials/michael-b.jpg",
      rating: 5,
      content: "I was struggling with physics, but thanks to the books and practice questions recommended by EduAI, it has now become my favorite subject.",
      date: "2024-12-10",
      featured: false,
      tags: ["physics", "middleschool", "book-recommendations"]
    }
  ],

  cta: {
    title: "Start Your Learning Journey with EduAI",
    subtitle: "Future of Education Technology",
    description: "Reach your academic goals with AI-powered personalized learning experience. Like thousands of students, you too can increase your success.",
    primaryCTA: {
      text: "Start Free",
      href: "/register",
      ariaLabel: "Sign up for EduAI free and start learning"
    },
    secondaryCTA: {
      text: "Watch Demo",
      href: "/demo",
      ariaLabel: "Watch EduAI platform demo video"
    },
    socialProof: {
      userCount: "50,000+",
      rating: 4.8,
      recentSignups: "1,200+ new students joined this week"
    },
    riskReduction: [
      "Free trial period",
      "No credit card required",
      "Cancel anytime",
      "24/7 technical support"
    ]
  },

  footer: {
    brand: {
      name: "EduAI",
      description: "AI-powered personalized education platform. Optimize your learning process, reach your goals faster.",
      logo: "/images/logo-white.svg"
    },
    navigation: {
      product: {
        title: "Product",
        links: [
          { name: "Features", href: "#features" },
          { name: "How It Works", href: "#how-it-works" },
          { name: "Pricing", href: "/pricing" },
          { name: "Demo", href: "/demo" }
        ]
      },
      support: {
        title: "Support",
        links: [
          { name: "Help Center", href: "/help" },
          { name: "Contact", href: "/contact" },
          { name: "FAQ", href: "/faq" },
          { name: "Live Support", href: "/support" }
        ]
      },
      company: {
        title: "Company",
        links: [
          { name: "About Us", href: "/about" },
          { name: "Blog", href: "/blog" },
          { name: "Careers", href: "/careers" },
          { name: "Press Kit", href: "/press" }
        ]
      },
      legal: {
        title: "Legal",
        links: [
          { name: "Privacy Policy", href: "/privacy" },
          { name: "Terms of Service", href: "/terms" },
          { name: "GDPR", href: "/gdpr" },
          { name: "Cookie Policy", href: "/cookies" }
        ]
      }
    },
    social: [
      {
        name: "Facebook",
        href: "https://facebook.com/eduai",
        icon: "facebook",
        ariaLabel: "Visit our Facebook page"
      },
      {
        name: "Twitter",
        href: "https://twitter.com/eduai",
        icon: "twitter",
        ariaLabel: "Follow our Twitter account"
      },
      {
        name: "LinkedIn",
        href: "https://linkedin.com/company/eduai",
        icon: "linkedin",
        ariaLabel: "Visit our LinkedIn page"
      },
      {
        name: "Instagram",
        href: "https://instagram.com/eduai",
        icon: "instagram",
        ariaLabel: "Follow our Instagram account"
      },
      {
        name: "YouTube",
        href: "https://youtube.com/eduai",
        icon: "youtube",
        ariaLabel: "Subscribe to our YouTube channel"
      }
    ],
    newsletter: {
      title: "Subscribe to Our Newsletter",
      description: "Join our email list for EduAI updates and education tips.",
      placeholder: "Your email address",
      buttonText: "Subscribe"
    },
    legal: {
      copyright: "© 2025 EduAI. All rights reserved.",
      links: [
        { name: "Privacy", href: "/privacy" },
        { name: "Terms", href: "/terms" },
        { name: "Cookies", href: "/cookies" }
      ],
      madeWith: "Made with ❤️ in Turkey"
    }
  }
};

// Localization manager
export interface LocalizationConfig {
  defaultLanguage: string;
  supportedLanguages: string[];
  fallbackLanguage: string;
  rtlLanguages: string[];
}

export class LocalizationManager {
  private static instance: LocalizationManager;
  private currentLanguage: string;
  private config: LocalizationConfig;
  private translations: Map<string, LocalizedContent>;

  private constructor() {
    this.config = {
      defaultLanguage: 'tr',
      supportedLanguages: ['tr', 'en'],
      fallbackLanguage: 'tr',
      rtlLanguages: ['ar']
    };
    this.currentLanguage = this.config.defaultLanguage;
    this.translations = new Map();
    
    // Load English translations
    this.translations.set('en', englishContent);
  }

  static getInstance(): LocalizationManager {
    if (!LocalizationManager.instance) {
      LocalizationManager.instance = new LocalizationManager();
    }
    return LocalizationManager.instance;
  }

  // Language management
  setLanguage(languageCode: string): boolean {
    if (this.config.supportedLanguages.includes(languageCode)) {
      this.currentLanguage = languageCode;
      return true;
    }
    return false;
  }

  getCurrentLanguage(): string {
    return this.currentLanguage;
  }

  getSupportedLanguages(): string[] {
    return [...this.config.supportedLanguages];
  }

  isRTL(languageCode?: string): boolean {
    const lang = languageCode || this.currentLanguage;
    return this.config.rtlLanguages.includes(lang);
  }

  // Content retrieval
  getContent(languageCode?: string): LocalizedContent {
    const lang = languageCode || this.currentLanguage;
    
    // Return English content if available
    if (lang === 'en' && this.translations.has('en')) {
      return this.translations.get('en')!;
    }
    
    // For Turkish or unsupported languages, return Turkish content
    // We'll load it from the data file directly
    return this.getTurkishContent();
  }

  private getTurkishContent(): LocalizedContent {
    // Return Turkish content from the main content file
    // This avoids circular imports by not importing here
    return {
      hero: {
        title: "AI ile Kişiselleştirilmiş Eğitim Deneyimi",
        subtitle: "Geleceğin Öğrenme Platformu",
        description: "EduAI ile yapay zeka destekli soru üretimi, detaylı performans analizi ve kişiselleştirilmiş kitap önerileri sayesinde öğrenme hedeflerinize daha hızlı ulaşın. Binlerce öğrenci akademik başarısını artırdı.",
        primaryCTA: {
          text: "Ücretsiz Başla",
          href: "/register",
          ariaLabel: "EduAI'ye ücretsiz kaydol"
        },
        secondaryCTA: {
          text: "Demo İzle",
          href: "/demo",
          ariaLabel: "EduAI demo videosunu izle"
        },
        features: [
          "AI destekli soru üretimi",
          "Detaylı performans analizi",
          "Kişiselleştirilmiş öğrenme",
          "7/24 destek"
        ],
        trustIndicators: {
          userCount: "50,000+",
          rating: 4.8,
          testimonialPreview: "EduAI sayesinde matematik notlarım %40 arttı!"
        }
      },
      features: [],
      workflow: [],
      statistics: [],
      testimonials: [],
      cta: {
        title: "EduAI ile Öğrenme Yolculuğuna Başla",
        subtitle: "Geleceğin Eğitim Teknolojisi",
        description: "Yapay zeka destekli kişiselleştirilmiş eğitim deneyimi ile akademik hedeflerinize ulaşın. Binlerce öğrenci gibi siz de başarınızı artırın.",
        primaryCTA: {
          text: "Ücretsiz Başla",
          href: "/register",
          ariaLabel: "EduAI'ye ücretsiz kaydol ve öğrenmeye başla"
        },
        secondaryCTA: {
          text: "Demo İzle",
          href: "/demo",
          ariaLabel: "EduAI platformu demo videosunu izle"
        },
        socialProof: {
          userCount: "50,000+",
          rating: 4.8,
          recentSignups: "Bu hafta 1,200+ yeni öğrenci katıldı"
        },
        riskReduction: [
          "Ücretsiz deneme süresi",
          "Kredi kartı bilgisi gerektirmez",
          "İstediğiniz zaman iptal edebilirsiniz",
          "7/24 teknik destek"
        ]
      },
      footer: {
        brand: {
          name: "EduAI",
          description: "Yapay zeka destekli kişiselleştirilmiş eğitim platformu.",
          logo: "/images/logo-white.svg"
        },
        navigation: {
          product: {
            title: "Ürün",
            links: []
          }
        },
        social: [],
        newsletter: {
          title: "Bültenimize Abone Olun",
          description: "EduAI'daki yenilikler için e-posta listemize katılın.",
          placeholder: "E-posta adresiniz",
          buttonText: "Abone Ol"
        },
        legal: {
          copyright: "© 2025 EduAI. Tüm hakları saklıdır.",
          links: [],
          madeWith: "Made with ❤️ in Turkey"
        }
      }
    };
  }

  // Translation utilities
  translate(key: string, languageCode?: string): string {
    const lang = languageCode || this.currentLanguage;
    const content = this.getContent(lang);
    
    // Simple key-based translation lookup
    const keys = key.split('.');
    let value: any = content;
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }
    
    return typeof value === 'string' ? value : key;
  }

  // Localized formatting
  formatNumber(num: number, languageCode?: string): string {
    const lang = languageCode || this.currentLanguage;
    
    try {
      return new Intl.NumberFormat(lang === 'tr' ? 'tr-TR' : 'en-US').format(num);
    } catch {
      return num.toString();
    }
  }

  formatDate(date: Date, languageCode?: string): string {
    const lang = languageCode || this.currentLanguage;
    
    try {
      return new Intl.DateTimeFormat(lang === 'tr' ? 'tr-TR' : 'en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      }).format(date);
    } catch {
      return date.toISOString().split('T')[0];
    }
  }

  formatCurrency(amount: number, currency: string = 'TRY', languageCode?: string): string {
    const lang = languageCode || this.currentLanguage;
    
    try {
      return new Intl.NumberFormat(lang === 'tr' ? 'tr-TR' : 'en-US', {
        style: 'currency',
        currency: currency
      }).format(amount);
    } catch {
      return `${amount} ${currency}`;
    }
  }
}

// React hooks for localization
export const useLocalization = () => {
  const localizationManager = LocalizationManager.getInstance();
  
  return {
    currentLanguage: localizationManager.getCurrentLanguage(),
    setLanguage: (lang: string) => localizationManager.setLanguage(lang),
    supportedLanguages: localizationManager.getSupportedLanguages(),
    isRTL: (lang?: string) => localizationManager.isRTL(lang),
    getContent: (lang?: string) => localizationManager.getContent(lang),
    translate: (key: string, lang?: string) => localizationManager.translate(key, lang),
    formatNumber: (num: number, lang?: string) => localizationManager.formatNumber(num, lang),
    formatDate: (date: Date, lang?: string) => localizationManager.formatDate(date, lang),
    formatCurrency: (amount: number, currency?: string, lang?: string) => 
      localizationManager.formatCurrency(amount, currency, lang)
  };
};

// Language detection utilities
export const detectBrowserLanguage = (): string => {
  if (typeof window !== 'undefined') {
    const browserLang = navigator.language.split('-')[0];
    const supportedLanguages = ['tr', 'en'];
    return supportedLanguages.includes(browserLang) ? browserLang : 'tr';
  }
  return 'tr';
};

// Export for easy import
export default LocalizationManager;
